import sys
import os
from dotenv import load_dotenv

# 1. CRITICAL: LOAD ENV VARIABLES FIRST BEFORE ANY CODE RUNS
# Load root .env file and server .env file into environment memory
ROOT_ENV_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '.env'))
SERVER_ENV_PATH = os.path.join(os.path.dirname(__file__), '.env')
load_dotenv(ROOT_ENV_PATH, override=False)
load_dotenv(SERVER_ENV_PATH, override=False)

# 2. Setup directory lookup parameters for path mapping
BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
PARENT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '../..'))
PROJECT_ROOT = PARENT_DIR
if not os.path.exists(os.path.join(PROJECT_ROOT, 'frontend-admin')) and os.path.exists('/app/frontend-admin'):
    PROJECT_ROOT = '/app'

sys.path.append(BASE_DIR)
sys.path.append(PARENT_DIR)
sys.path.append(os.path.join(BASE_DIR, 'admin_backend'))
sys.path.append(os.path.join(BASE_DIR, 'backend_staff'))
sys.path.append(os.path.join(BASE_DIR, 'backend_canteen'))
sys.path.append(os.path.join(BASE_DIR, 'registration_backend'))
sys.path.append(os.path.join(PROJECT_ROOT, 'admin_backend'))
sys.path.append(os.path.join(PROJECT_ROOT, 'backend_staff'))
sys.path.append(os.path.join(PROJECT_ROOT, 'backend_canteen'))
sys.path.append(os.path.join(PROJECT_ROOT, 'registration_backend'))

from flask import Flask, jsonify
from flask_cors import CORS
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

from admin_backend.extensions import db 

# Import the Blueprint objects generated by your agent

from admin_backend.app import admin_bp
from backend_staff.app import staff_bp
from backend_canteen.app import canteen_bp
from registration_backend.app import reg_bp 
from blueprints.student_api import student_bp

# 3. Initialize the global Flask application instance
app = Flask(__name__)
app.config['PROPAGATE_EXCEPTIONS'] = True

from werkzeug.exceptions import HTTPException

@app.errorhandler(Exception)
def handle_global_exception(e):
    if isinstance(e, HTTPException):
        return e
    import traceback
    print("GLOBAL EXCEPTION TRACEBACK:", flush=True)
    traceback.print_exc()
    return jsonify({"error": str(e), "traceback": traceback.format_exc()}), 500

from urllib.parse import quote_plus

# Dynamically builds the database connection using environment variables
is_docker = os.path.exists('/.dockerenv') or os.path.exists('/app/frontend-admin')
default_host = 'db' if is_docker else '127.0.0.1'

db_user = os.getenv('MYSQL_USER', 'meal_app')
db_pass = os.getenv('MYSQL_PASSWORD', 'Admin@RKMVC2')
db_host = os.getenv('MYSQL_HOST', os.getenv('DB_HOST', default_host))
db_port = os.getenv('MYSQL_PORT', os.getenv('DB_PORT', '3306'))
db_name = os.getenv('MYSQL_DATABASE', 'rkmvc_mealflow_db')

encoded_pass = quote_plus(db_pass)
app.config['SQLALCHEMY_DATABASE_URI'] = f'mysql+pymysql://{db_user}:{encoded_pass}@{db_host}:{db_port}/{db_name}'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db.init_app(app)

# 4. Global Security Settings & CORS Flexibility
CORS(app, resources={r"/*": {"origins": ["http://localhost:5173", "http://localhost:3000", "http://localhost:5050", "http://127.0.0.1:5173", "http://127.0.0.1:3000", "http://127.0.0.1:5050", "*"]}}, supports_credentials=True) 
app.config['MAX_CONTENT_LENGTH'] = 16 * 1024 * 1024  # Sets 16MB file limit for Registration Form

# 5. Connect the Admin Rate Limiter to the central app context
limiter = Limiter(get_remote_address, app=app, default_limits=["50000 per day", "10000 per hour"])

# Ensure defensive server file buffer directories exist on disk
UPLOAD_SUBDIRS = ['student_signatures', 'income_proofs', 'student_master_img']
active_uploads_dir = os.path.join(BASE_DIR, 'registration_backend', 'uploads')
for sub in UPLOAD_SUBDIRS:
    os.makedirs(os.path.join(active_uploads_dir, sub), exist_ok=True)
os.makedirs(os.path.join(BASE_DIR, 'registration_backend', 'generated_pdfs'), exist_ok=True)

# Ensure database tables and seed default users (admin/staff) on startup
with app.app_context():
    try:
        from admin_backend.app import get_db, _ensure_tables
        conn = get_db()
        _ensure_tables(conn)
        conn.close()
        print("--- DB SCHEMAS AND SEED USERS INITIALIZED ---", flush=True)
    except Exception as e:
        print("--- DB INIT WARNING ---:", e, flush=True)

# 6. Mount the Blueprints to their new shared web prefixes
app.register_blueprint(admin_bp, url_prefix='/api/admin')
app.register_blueprint(staff_bp, url_prefix='/api/staff')
app.register_blueprint(canteen_bp, url_prefix='/api/canteen')
app.register_blueprint(reg_bp, url_prefix='/api/register')
app.register_blueprint(student_bp, url_prefix='/api/student')

@app.route('/api/public/meal-config', methods=['GET'])
def get_public_meal_config():
    from admin_backend.app import get_db, _get_meal_config
    conn = get_db()
    try:
        cfg = _get_meal_config(conn)
        return jsonify(cfg)
    finally:
        conn.close()

# 7. Helper to serve built SPA frontends from their dist directories
from flask import send_from_directory, render_template_string, redirect

def configure_frontend_route(prefix, relative_dist_path):
    abs_dist_path = os.path.abspath(os.path.join(PROJECT_ROOT, relative_dist_path))
    endpoint_name = f"serve_frontend_{prefix.strip('/')}"
    
    @app.route(f'{prefix}', endpoint=f"{endpoint_name}_redirect")
    def serve_frontend_redirect():
        return redirect(f'{prefix}/')

    @app.route(f'{prefix}/', endpoint=f"{endpoint_name}_root")
    @app.route(f'{prefix}/<path:path>', endpoint=endpoint_name)
    def serve_frontend_files(path=''):
        file_path = os.path.join(abs_dist_path, path)
        if path and os.path.exists(file_path) and os.path.isfile(file_path):
            resp = send_from_directory(abs_dist_path, path)
            resp.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'
            resp.headers['Pragma'] = 'no-cache'
            resp.headers['Expires'] = '0'
            return resp
        resp = send_from_directory(abs_dist_path, 'index.html')
        resp.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'
        resp.headers['Pragma'] = 'no-cache'
        resp.headers['Expires'] = '0'
        return resp

# Setup routes for all frontends
configure_frontend_route('/admin', 'frontend-admin/dist')
configure_frontend_route('/admin-login', 'frontend-admin/dist')
configure_frontend_route('/staff', 'frontend-staff/dist')
configure_frontend_route('/canteen', 'frontend-canteen/dist')
configure_frontend_route('/student', 'frontend-stud/dist')
configure_frontend_route('/register', 'frontend-reg/dist')


# Convenient Redirect Aliases for manual URL typing
@app.route('/db')
@app.route('/database')
@app.route('/tables')
def db_redirect():
    return redirect('/admin/')

@app.route('/login')
@app.route('/signin')
@app.route('/canteen-login')
@app.route('/staff-login')
def login_redirect():
    return redirect('/admin-login/')

# 8. Server Static File Pointer Routes
@app.route('/uploads/<path:filename>')
def serve_global_uploads(filename):
    uploads_dir1 = os.path.join(BASE_DIR, 'registration_backend', 'uploads')
    uploads_dir2 = os.path.join(PROJECT_ROOT, 'uploads')
    
    target_filename = filename
    if filename.startswith('student_photos/'):
        target_filename = filename.replace('student_photos/', 'student_master_img/', 1)
    elif filename.startswith('student_images/'):
        target_filename = filename.replace('student_images/', 'student_master_img/', 1)
    elif filename.startswith('signatures/'):
        target_filename = filename.replace('signatures/', 'student_signatures/', 1)
    elif filename.startswith('students/'):
        target_filename = filename.replace('students/', 'student_master_img/', 1)

    for candidate in [target_filename, filename]:
        if os.path.exists(os.path.join(uploads_dir1, candidate)):
            return send_from_directory(uploads_dir1, candidate)
        if os.path.exists(os.path.join(uploads_dir2, candidate)):
            return send_from_directory(uploads_dir2, candidate)

    return send_from_directory(uploads_dir1, target_filename)

@app.route('/generated_pdfs/<path:filename>')
def serve_global_pdfs(filename):
    pdfs_dir = os.path.join(BASE_DIR, 'registration_backend', 'generated_pdfs')
    return send_from_directory(pdfs_dir, filename)

# 9. Sleek Glassmorphic Landing Portal
LANDING_HTML = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RKMVC Meal Flow — Centralized Dining Portal</title>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;800&display=swap" rel="stylesheet">
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: 'Outfit', sans-serif;
            background: linear-gradient(135deg, #fffaf3 0%, #fff1e0 100%);
            color: #431407;
            min-height: 100vh;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            overflow-x: hidden;
        }
        .container {
            max-width: 1200px;
            width: 100%;
            padding: 2rem;
            text-align: center;
            z-index: 10;
        }
        header {
            margin-bottom: 3.5rem;
            animation: fadeInDown 0.8s ease-out;
        }
        .logo-glow {
            width: 120px;
            height: 120px;
            margin: 0 auto 1.5rem;
            background: radial-gradient(circle, rgba(249,115,22,0.15) 0%, rgba(255,255,255,0) 70%);
            display: flex;
            align-items: center;
            justify-content: center;
            border-radius: 50%;
        }
        .logo-glow img {
            width: 100px;
            height: 100px;
            object-fit: contain;
            border-radius: 50%;
            background: #ffffff;
            padding: 6px;
            box-shadow: 0 4px 20px rgba(249, 115, 22, 0.25);
        }
        h1 {
            font-size: 3rem;
            font-weight: 800;
            background: linear-gradient(to right, #ea580c, #f97316, #fb923c);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            letter-spacing: -0.03em;
            margin-bottom: 0.75rem;
        }
        p.subtitle {
            font-size: 1.15rem;
            color: #7c4a2d;
            max-width: 600px;
            margin: 0 auto;
            line-height: 1.6;
        }
        .grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 2rem;
            margin-top: 1.5rem;
            perspective: 1000px;
        }
        .card {
            background: rgba(255, 255, 255, 0.75);
            backdrop-filter: blur(12px);
            -webkit-backdrop-filter: blur(12px);
            border: 1px solid rgba(249, 115, 22, 0.15);
            border-radius: 20px;
            padding: 2.25rem 1.75rem;
            text-decoration: none;
            color: inherit;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: space-between;
            transition: all 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275);
            cursor: pointer;
            box-shadow: 0 4px 30px rgba(249, 115, 22, 0.08);
            position: relative;
            overflow: hidden;
            animation: scaleIn 0.6s ease-out both;
        }
        .card::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: linear-gradient(135deg, rgba(249,115,22,0.08) 0%, rgba(251,146,60,0.04) 100%);
            opacity: 0;
            transition: opacity 0.3s ease;
        }
        .card:hover {
            transform: translateY(-8px) scale(1.03);
            border-color: rgba(249, 115, 22, 0.5);
            box-shadow: 0 10px 40px rgba(249, 115, 22, 0.2);
        }
        .card:hover::before {
            opacity: 1;
        }
        .card-icon {
            font-size: 2.5rem;
            margin-bottom: 1.25rem;
            background: rgba(249, 115, 22, 0.1);
            width: 70px;
            height: 70px;
            display: flex;
            align-items: center;
            justify-content: center;
            border-radius: 50%;
            border: 1px solid rgba(249, 115, 22, 0.25);
            transition: all 0.3s ease;
        }
        .card:hover .card-icon {
            transform: rotate(10deg) scale(1.1);
            background: rgba(249, 115, 22, 0.2);
            border-color: rgba(249, 115, 22, 0.4);
        }
        h2 {
            font-size: 1.35rem;
            font-weight: 600;
            color: #7c2d12;
            margin-bottom: 0.5rem;
        }
        .card-desc {
            font-size: 0.9rem;
            color: #92602f;
            line-height: 1.5;
            margin-bottom: 1.5rem;
        }
        .badge {
            font-size: 0.75rem;
            font-weight: 600;
            letter-spacing: 0.05em;
            text-transform: uppercase;
            padding: 0.35rem 0.75rem;
            border-radius: 30px;
            background: rgba(249, 115, 22, 0.08);
            border: 1px solid rgba(249, 115, 22, 0.2);
            color: #c2410c;
            transition: all 0.3s ease;
        }
        .card:hover .badge {
            background: rgba(249, 115, 22, 0.2);
            border-color: rgba(249, 115, 22, 0.4);
            color: #9a3412;
        }
        footer {
            margin-top: 5rem;
            font-size: 0.85rem;
            color: #b45309;
            z-index: 10;
        }
        @keyframes fadeInDown {
            from {
                opacity: 0;
                transform: translateY(-20px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }
        @keyframes scaleIn {
            from {
                opacity: 0;
                transform: scale(0.9);
            }
            to {
                opacity: 1;
                transform: scale(1);
            }
        }
        .card:nth-child(1) { animation-delay: 0.1s; }
        .card:nth-child(2) { animation-delay: 0.2s; }
        .card:nth-child(3) { animation-delay: 0.3s; }
        .card:nth-child(4) { animation-delay: 0.4s; }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <div class="logo-glow">
                <img src="/static/rkm_logo.png" alt="Ramakrishna Mission Logo">
            </div>
            <h1>RKMVC Meal Flow</h1>
            <p class="subtitle">Unified Portal Hub for Ramakrishna Mission Vivekananda College Free Noon Meals Scheme</p>
        </header>

        <div class="grid">
            <a href="/admin-login/" class="card">
                <div class="card-icon">🔑</div>
                <div>
                    <h2>Admin & Staff Login</h2>
                    <p class="card-desc">Login portal for administrators, approval wardens, and canteen staff operators.</p>
                </div>
                <span class="badge">Management</span>
            </a>

            <a href="/staff/" class="card">
                <div class="card-icon">🍳</div>
                <div>
                    <h2>Staff Portal</h2>
                    <p class="card-desc">Dining token creation, real-time student verification, terminal barcode scanner controls.</p>
                </div>
                <span class="badge">Dining Operations</span>
            </a>

            <a href="/canteen/" class="card">
                <div class="card-icon">🍱</div>
                <div>
                    <h2>Canteen Portal</h2>
                    <p class="card-desc">Canteen counter redemption terminal, meal distribution scanning, and real-time claim logs.</p>
                </div>
                <span class="badge">Canteen Counter</span>
            </a>


            <a href="/student/" class="card">
                <div class="card-icon">🎓</div>
                <div>
                    <h2>Student Portal</h2>
                    <p class="card-desc">Access student dashboard, view breakfast & lunch eligibility, display dynamic security QR codes.</p>
                </div>
                <span class="badge">Self-Service</span>
            </a>

            <a href="/register/" class="card">
                <div class="card-icon">📝</div>
                <div>
                    <h2>Registration Form</h2>
                    <p class="card-desc">Public registration portal for new students to submit free meal scheme applications.</p>
                </div>
                <span class="badge">Scheme Signup</span>
            </a>
        </div>

        <footer>
            &copy; 2026 Ramakrishna Mission Vivekananda College. All rights reserved.
        </footer>
    </div>
</body>
</html>
"""

from flask import make_response

@app.route('/')
def home():
    resp = make_response(render_template_string(LANDING_HTML))
    resp.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'
    resp.headers['Pragma'] = 'no-cache'
    resp.headers['Expires'] = '0'
    return resp

if __name__ == '__main__':
    # Starts your single backend engine on port 5050 (or PORT env var)
    port = int(os.environ.get('PORT', 5050))
    app.run(host='0.0.0.0', port=port, debug=False)

